apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovue
  labels:
    app: hellovue
spec:
  selector:
    matchLabels:
      app: hellovue
  replicas: 1
  template:
    metadata:
      name: hellovue
      labels:
        app: hellovue
    spec:
      containers:
        - name: hellovue
          image: docker.io/hiondal/hellovue:latest
          imagePullPolicy: Always
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: hellovue
spec:
  type: ClusterIP
  selector:
    app: hellovue
  ports:
    - name: hellovue
      port: 8080
      targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hellovue
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: hellovue-u00.165.192.105.60.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: hellovue
                port: 
                  number: 8080
